# Generated by Django 2.0.4 on 2018-04-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('prevista', models.BooleanField(default=False)),
                ('registrada', models.BooleanField(default=False)),
                ('resolvido', models.BooleanField(default=False)),
                ('numero_de_aulas_prevista', models.IntegerField(default=0)),
                ('numero_de_aulas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('creditos', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], max_length=1)),
                ('numero_de_aulas', models.IntegerField(default=0)),
                ('diario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('nome', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Turma'),
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Disciplina'),
        ),
        migrations.AddField(
            model_name='diario',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestao-Diarios.Professor'),
        ),
        migrations.AddField(
            model_name='aula',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao-Diarios.Diario'),
        ),
    ]
