# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero_de_aulas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('creditos', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
                ('professor', models.CharField(max_length=120)),
                ('turma', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestao-Diarios.Disciplina'),
        ),
        migrations.AddField(
            model_name='aula',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao-Diarios.Diario'),
        ),
    ]
