# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao-Diarios', '0002_auto_20170419_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='numero_de_aulas_prevista',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aula',
            name='prevista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aula',
            name='registrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='numero_de_aulas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao-Diarios.Turma'),
        ),
    ]
