# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao-Diarios', '0003_auto_20170424_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], max_length=1)),
                ('numero_de_aulas', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='numero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao-Diarios.Diario'),
        ),
    ]
