# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao-Diarios', '0005_auto_20170508_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
